LapShop/LapShop-Project/Controllers/ItemsController.cs
using Bl.Classes;

namespace LapShop_Project.Controllers
{
    public class ItemsController : Controller
    {
        private readonly Iitems oClsItems;
        private readonly IItemImages oClsItemIamges;
        private readonly VmItemDetails VM;

        // Constrictor
        public ItemsController(Iitems oClsItems, IItemImages oClsItemIamges)
        {
            this.oClsItems = oClsItems;
            VM = new VmItemDetails();
            this.oClsItemIamges = oClsItemIamges;
        }

        // Method
        public IActionResult ItemsDetails(int id)
        {
            VM.Item = oClsItems.GetItemById(id);
            VM.ListItemImages = oClsItemIamges.GetByItemId(id);
            VM.ListRecommendedItems = oClsItems.GetRecommendedItems(id).Take(18).ToList();
            return View(VM);
        }
        public IActionResult ItemList()
        {
            return View();
        }


    }
}

LapShop/LapShop-Project/Controllers/OrderController.cs
using Bl.Classes;

namespace LapShop_Project.Controllers
{
    public class OrderController : Controller
    {
        private readonly Iitems ItemService;
        private ShoppingCard cart;
        private UserManager<ApplicationUser> _userManager;
        private ISalesInvoice oClsSalesInvoice;


        // Constrictor
        public OrderController(Iitems ItemService, UserManager<ApplicationUser> userManager, ISalesInvoice oClsSalesInvoice)
        {
            this.ItemService = ItemService;
            cart = new ShoppingCard();
            _userManager = userManager;
            this.oClsSalesInvoice = oClsSalesInvoice;
        }


        private void SetCartItems(List<ShoppingCard> cartItems)
        {
            var cartJson = JsonConvert.SerializeObject(cartItems);
            CookieOptions options = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(7),
                Path = "/"
            };
            Response.Cookies.Append("Cart", cartJson, options);
        }


        // Method 
        [HttpGet]
        public IActionResult Cart()
        {
            string sSessionCart = string.Empty;
            ShoppingCard? card = new ShoppingCard();
            // get session && check session null
            if (HttpContext.Request.Cookies["Cart"] != null)
            {
                sSessionCart = HttpContext.Request.Cookies["Cart"];

                card = JsonConvert.DeserializeObject<ShoppingCard>(sSessionCart);
            }


            return View(card);
        }

        public IActionResult AddToCart(int itemId)
        {

            //check session null
            if (HttpContext.Request.Cookies["Cart"] != null)
                cart = JsonConvert.DeserializeObject<ShoppingCard>(HttpContext.Request.Cookies["Cart"]);

            var item = ItemService.GetById(itemId);

            var itemInList = cart.ListItems.Where(c => c.ItemId == itemId).FirstOrDefault();

            // check listItem == null
            if (itemInList != null)
            {
                itemInList.Qty++;
                itemInList.Total = itemInList.Qty * itemInList.Price;
            }
            else
            {
                // set data in list item
                cart.ListItems.Add(new ShoppingCardItem()
                {
                    ItemId = item.ItemId,
                    ItemName = item.ItemName,
                    ImageName = item.ImageName,
                    Price = item.SalesPrice,
                    Qty = 1,
                    Total = item.SalesPrice
                });
            }

            // sum total price 
            cart.Total = cart.ListItems.Sum(c => c.Total);


            // set Session
            HttpContext.Response.Cookies.Append("Cart", JsonConvert.SerializeObject(cart));
            //HttpContext.Session.SetString("Cart", JsonConvert.SerializeObject(cart));

            return RedirectToAction(nameof(Cart));
        }


        [HttpGet]
        public async Task<IActionResult> MyOrders()
        {
            var user = await _userManager.GetUserAsync(User);
            var ListInvoice = oClsSalesInvoice.GetById(Guid.Parse(user.Id));
            ViewBag.Invoice = ListInvoice[0];

            return View(nameof(OrderSuccess), ListInvoice);
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> OrderSuccess(string myCard)
        {

            var myCardList = new ShoppingCard();
            string sSessionCart = string.Empty;

            if (HttpContext.Request.Cookies["Cart"] != null)
                sSessionCart = HttpContext.Request.Cookies["Cart"];
            var cart = JsonConvert.DeserializeObject<ShoppingCard>(sSessionCart);

            // check as cart 
            if (cart == null)
            {
                TempData["ErrorMessage"] = "Shopping cart is empty.";
                return Redirect("/Order/Cart");
            }
            // set  ShoppingCard
            if (!string.IsNullOrEmpty(myCard)) myCardList = JsonConvert.DeserializeObject<ShoppingCard>(myCard);
            else
            {
                TempData["ErrorMessage"] = "Not Found.";
                return Redirect("/Order/Cart");
            }
            // save order
            await SaveOrder(cart);

            // remove  cookies
            HttpContext.Response.Cookies.Delete("Cart");

            // add id user 
            var user = await _userManager.GetUserAsync(User);
            var ListInvoice = oClsSalesInvoice.GetById(Guid.Parse(user.Id));
            ViewBag.Invoice = ListInvoice[0];

            return View(ListInvoice);
        }

        public async Task SaveOrder(ShoppingCard oShoppingCard)
        {
            try
            {
                List<TbSalesInvoiceItem> lstInvoiceItems = new List<TbSalesInvoiceItem>();

                //
                foreach (var item in oShoppingCard.ListItems)
                {
                    lstInvoiceItems.Add(new TbSalesInvoiceItem()
                    {
                        ItemId = item.ItemId,
                        Qty = item.Qty,
                        InvoicePrice = item.Price
                    });
                }

                var user = await _userManager.GetUserAsync(User);

                //
                TbSalesInvoice oSalesInvoice = new TbSalesInvoice()
                {
                    InvoiceDate = DateTime.Now,
                    CustomerId = Guid.Parse(user.Id),
                    DelivryDate = DateTime.Now.AddDays(5),
                    CreatedBy = user.UserName,
                    CreatedDate = DateTime.Now
                };

                oClsSalesInvoice.Save(oSalesInvoice, lstInvoiceItems, true, user.UserName);
            }
            catch (Exception)
            {
                throw new Exception();
            }
        }

        // logic
        private void SetCart(ShoppingCard cart)
        {
            var cartCookieValue = JsonConvert.SerializeObject(cart);
            CookieOptions options = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(7), // صلاحية الكوكي
                HttpOnly = true
            };
            HttpContext.Response.Cookies.Append("Cart", cartCookieValue, options);
        }
        private ShoppingCard GetCart()
        {
            var cartCookie = HttpContext.Request.Cookies["Cart"];

            if (!string.IsNullOrEmpty(cartCookie))
            {
                return JsonConvert.DeserializeObject<ShoppingCard>(cartCookie);
            }
            return new ShoppingCard(); // إنشاء سلة جديدة إذا كانت فارغة
        }
        public IActionResult RemoveFromCart(int productId)
        {
            // استرجاع سلة التسوق من الكوكي
            var cart = GetCart();

            // حذف العنصر الذي يحمل ItemId المطابق
            cart.ListItems = cart.ListItems.Where(item => item.ItemId != productId).ToList();

            // إعادة حساب المجموع الإجمالي بعد الحذف
            cart.Total = cart.ListItems.Sum(item => item.Total);


            // إعادة تحديث الكوكي بسلة التسوق المحدثة
            SetCart(cart);

            return RedirectToAction("Cart"); // إعادة التوجيه إلى صفحة السلة
        }
    }
}

LapShop/LapShop-Project/Views/Order/Cart.cshtml
@model ShoppingCard
@{
    ViewData["Title"] = "Cart";

    var myCardJson = Json.Serialize(Model);
}
<!-- breadcrumb start -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="page-title">
                    <h2>Cart</h2>
                </div>
            </div>
            <div class="col-sm-6">
                <nav aria-label="breadcrumb" class="theme-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/Home/Index">Home</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb End -->
<!--section start-->
<section class="cart-section section-b-space">
    @if (TempData["ErrorMessage"] != null)
    {
        <div style="text-align:center;" class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <table class="table cart-table table-responsive-xs">
                    <thead>
                        <tr class="table-head">
                            <th scope="col">@ResPage.lblImage</th>
                            <th scope="col">@ResPage.lblProductName</th>
                            <th scope="col">@ResPage.lblPrice</th>
                            <th scope="col">@ResPage.lblQuantity</th>
                            <th scope="col">@ResPage.lblAction</th>
                            <th scope="col">@ResPage.lblTotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListItems)
                        {
                            <tr>
                                <td>
                                    <a href="#"><img src="~/Uploads/Items/@item.ImageName" alt=""></a>
                                </td>
                                <td>
                                    <a asp-controller="Items" asp-action="ItemsDetails"
                                       asp-route-id="@item.ItemId">@item.ItemName</a>
                                </td>
                                <td>
                                    <h2>$@item.Price</h2>
                                </td>
                                <td>
                                    <div class="qty-box">
                                        <div class="input-group">
                                            <input type="number" name="quantity" class="form-control input-number"
                                                   data-id="@item.ItemId" data-price="@item.Price"
                                                   value="@item.Qty" onkeyup="ChangeQty(this)">
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a asp-controller="Order" asp-action="RemoveFromCart" asp-route-productId="@item.ItemId" class="icon">
                                        <i class="ti-close"></i>
                                    </a>

                                </td>
                                <td>
                                    <h2 data-id="@item.ItemId" class="td-color totalPrice">$@item.Total</h2>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <table class="table cart-table table-responsive-md">
                    <tfoot>
                        <tr>
                            <td>@ResPage.lblTotalPrice :</td>
                            <td>
                                <h2 id="overAllTotal">$@Model.Total</h2>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="row cart-buttons">
            <div class="col-6"><a href="/Home/Index" class="btn btn-solid">continue shopping</a></div>
            <div class="col-6">
                <a asp-controller="Order" asp-action="OrderSuccess" asp-route-myCard="@myCardJson"
                id="myButton" class="btn btn-solid">check out</a></div>
        </div>
    </div>
    </div>
</section>
<!--section end-->

<script>
    function ChangeQty(input) {
        let id = $(input).data("id");
        let price = $(input).data("price");
        let qty = $(input).val();
        let OverAllTotal = 0;

        // check total
        $(".totalPrice").each(function (i) {
            if ($(this).data("id") === id) {
                $(this).html("$" + (price * qty).toFixed(2));
            }

            OverAllTotal += parseFloat($(this).text().replace("$", ""));
        });

        // sum all total
        $("#overAllTotal").html("$" + OverAllTotal.toFixed(2));

        // ajax request
    }

   
    // let oShoppingCard = null; 

    // document.getElementById("myButton").addEventListener("click", function (event) {
    //     if (oShoppingCard === null) {
    //         event.preventDefault();
    //         alert("Shopping cart is empty.");
    //     }
    // });

</script>

LapShop/LapShop-Project/Views/Order/MyOrders.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LapShop/LapShop-Project/Views/Order/OrderSuccess.cshtml
@model List<VwSalesInvoice>
@{
    ViewData["Title"] = "Order Success";
    decimal nCount = 0;
}

<style>
    .order-container {
        text-align: center;
        margin: 30px auto;
        max-width: 700px;
        font-family: 'Open Sans', sans-serif;
        background-color: #ffffff;
        box-shadow: 0 6px 20px rgba(0, 0, 0, 0.1);
        padding: 40px;
        border-radius: 12px;
    }

        .order-container img {
            max-width: 100%;
            height: auto;
            margin-bottom: 20px;
            border-radius: 8px;
        }

    .order-detail {
        margin-top: 30px;
        border: 1px solid #e0e0e0;
        border-collapse: collapse;
        width: 100%;
        background-color: #fafafa;
    }

        .order-detail th,
        .order-detail td {
            padding: 15px;
            text-align: left;
            font-size: 15px;
            color: #444;
            border-bottom: 1px solid #e0e0e0;
        }

        .order-detail th {
            background-color: #f7f7f7;
            font-weight: bold;
            text-transform: capitalize;
        }

    .title {
        color: #333;
        font-size: 26px;
        font-weight: bold;
        text-transform: uppercase;
        margin-bottom: 15px;
    }

    .thank-you-text {
        font-size: 18px;
        color: #777;
        margin-bottom: 10px;
    }

    .total-row {
        font-weight: bold;
        background-color: #f7f7f7;
        text-align: right;
    }

    .total-cell {
        padding: 15px;
        font-size: 18px;
    }

</style>

<div class="order-container">
    <img src="~/FrontEnd/images/email-temp/delivery.png" alt="Delivery">
    <img src="~/FrontEnd/images/email-temp/success.png" alt="">
    <h2 class="title" style="padding:10px;align-items:center;">Thank You</h2>
    <p>Payment is successfully processed and your order is on the way.</p>

    <h4>Transaction ID: <b>56547747345374573</b></h4>
    <h6> User Name: <b>@ViewBag.Invoice.CreatedBy</b></h6>

    <table class="order-detail">
        <thead>
            <tr>
                <th>Product</th>
                <th>Item Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><img src="~/Uploads/Items/@item.ImageName" alt="Product Image" width="70"></td>
                    <td>@item.ItemName</td>
                    <td>@item.Qty</td>
                    <td><b>$@item.InvoicePrice</b></td>
                    <td><b>$@(@item.InvoicePrice * (decimal)@item.Qty)</b></td> <!-- Total per item -->
                </tr>
                nCount += (decimal)item.TotalPrice;
            }
                <!-- Display the total of all products -->
                <tr class="total-row">
                    <td colspan="4" class="total-cell">Total:</td>
                <td class="total-cell"><b>$@nCount</b></td> <!-- Total of all items -->
                </tr>
           
        </tbody>
    </table>


    <div class="address-section" style="margin-top: 30px;">
        <div style="float: left; width: 48%;">
            <h5>Delivery Address</h5>
            <p>268 Cambridge Lane, New Albany, IN 47150</p>
        </div>
        <div style="float: right; width: 48%;">
            <h5>Shipping Address</h5>
            <p>268 Cambridge Lane, New Albany, IN 47150</p>
        </div>
        <div style="clear: both;"></div>
    </div>
</div>